"""initial_tables

Revision ID: 4ff812e23e57
Revises: 
Create Date: 2026-01-02 18:14:30.307217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ff812e23e57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_stats')
    op.drop_index('ix_daily_indicators_date_instrument', table_name='daily_indicators')
    op.drop_table('daily_indicators')
    op.add_column('indicators_daily', sa.Column('ema_13', sa.Float(), nullable=True))
    op.add_column('indicators_daily', sa.Column('ema_26', sa.Float(), nullable=True))
    op.add_column('indicators_daily', sa.Column('ema_trend', sa.String(length=10), nullable=True))
    op.add_column('indicators_daily', sa.Column('ema_diff_pct', sa.Float(), nullable=True))
    op.add_column('indicators_daily', sa.Column('ema_13_slope', sa.Float(), nullable=True))
    op.add_column('indicators_daily', sa.Column('ema_26_slope', sa.Float(), nullable=True))
    op.add_column('indicators_daily', sa.Column('distance_to_ema_13_pct', sa.Float(), nullable=True))
    op.add_column('indicators_daily', sa.Column('distance_to_ema_26_pct', sa.Float(), nullable=True))
    op.add_column('instruments', sa.Column('exchange', sa.String(length=50), nullable=True))
    op.add_column('instruments', sa.Column('expiration_date', sa.Date(), nullable=True))
    op.add_column('instruments', sa.Column('basic_asset', sa.String(length=20), nullable=True))
    op.add_column('instruments', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('instruments', sa.Column('avg_spread_pct', sa.Float(), nullable=True))
    op.drop_column('instruments', 'spread_pct')
    op.add_column('signals', sa.Column('signal_date', sa.Date(), nullable=False))
    op.add_column('signals', sa.Column('position_value', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('max_loss', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('indicators_snapshot', sa.JSON(), nullable=True))
    op.alter_column('signals', 'signal_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index('ix_signals_date', 'signals', ['signal_date'], unique=False)
    op.create_index('ix_signals_instrument', 'signals', ['instrument_id'], unique=False)
    op.add_column('trades', sa.Column('signal_id', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('entry_date', sa.Date(), nullable=False))
    op.add_column('trades', sa.Column('exit_date', sa.Date(), nullable=True))
    op.alter_column('trades', 'entry_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('trades_entry_signal_id_fkey', 'trades', type_='foreignkey')
    op.create_foreign_key(None, 'trades', 'signals', ['signal_id'], ['id'])
    op.drop_column('trades', 'entry_signal_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('entry_signal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.create_foreign_key('trades_entry_signal_id_fkey', 'trades', 'signals', ['entry_signal_id'], ['id'])
    op.alter_column('trades', 'entry_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('trades', 'exit_date')
    op.drop_column('trades', 'entry_date')
    op.drop_column('trades', 'signal_id')
    op.drop_index('ix_signals_instrument', table_name='signals')
    op.drop_index('ix_signals_date', table_name='signals')
    op.alter_column('signals', 'signal_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('signals', 'indicators_snapshot')
    op.drop_column('signals', 'max_loss')
    op.drop_column('signals', 'position_value')
    op.drop_column('signals', 'signal_date')
    op.add_column('instruments', sa.Column('spread_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('instruments', 'avg_spread_pct')
    op.drop_column('instruments', 'is_active')
    op.drop_column('instruments', 'basic_asset')
    op.drop_column('instruments', 'expiration_date')
    op.drop_column('instruments', 'exchange')
    op.drop_column('indicators_daily', 'distance_to_ema_26_pct')
    op.drop_column('indicators_daily', 'distance_to_ema_13_pct')
    op.drop_column('indicators_daily', 'ema_26_slope')
    op.drop_column('indicators_daily', 'ema_13_slope')
    op.drop_column('indicators_daily', 'ema_diff_pct')
    op.drop_column('indicators_daily', 'ema_trend')
    op.drop_column('indicators_daily', 'ema_26')
    op.drop_column('indicators_daily', 'ema_13')
    op.create_table('daily_indicators',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('atr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('atr_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bb_upper', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bb_middle', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bb_lower', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bb_bandwidth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recommended_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stop_rub', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_loss_rub', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name='daily_indicators_instrument_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='daily_indicators_pkey'),
    sa.UniqueConstraint('instrument_id', 'date', name='uq_instrument_date')
    )
    op.create_index('ix_daily_indicators_date_instrument', 'daily_indicators', ['date', 'instrument_id'], unique=False)
    op.create_table('daily_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('trades_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('winning_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('losing_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_pnl_rub', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_pnl_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_drawdown_rub', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('start_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('end_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='daily_stats_pkey'),
    sa.UniqueConstraint('date', name='daily_stats_date_key')
    )
    # ### end Alembic commands ###
